alias pip='pip3'
alias python='python3'
alias ls='ls -G'
alias r='ranger'
alias v='vim'
alias bim='vim'
alias gprof='instruments'
alias grep='grep --color=auto'
alias gdb='lldb'
alias t='tmux'
alias emacs='emacs-24.5 -nw'
alias editnotes='vim ~/bin/notes'
alias mplay='mplayer -novideo'
alias maclogout="osascript -e 'tell application \"System Events\" to log out'"
